version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finance-db
    restart: unless-stopped
    env_file:
      - .envs/dev/db.env
    ports:
      - "5432:5432"
    volumes:
      - finance_db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: finance-backend
    restart: unless-stopped
    env_file:
      - .envs/dev/backend.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    container_name: finance-frontend
    restart: unless-stopped
    env_file:
      - .envs/dev/frontend.env
    depends_on:
      - backend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app

volumes:
  finance_db_data:
